export const PREMIERCONTACT_CREATE_REQUEST = 'PREMIERCONTACT_CREATE_REQUEST'
export const PREMIERCONTACT_CREATE_SUCCESS = 'PREMIERCONTACT_CREATE_SUCCESS'
export const PREMIERCONTACT_CREATE_FAIL = 'PREMIERCONTACT_CREATE_FAIL'
export const PREMIERCONTACT_CREATE_RESET = 'PREMIERCONTACT_CREATE_RESET'


export const PREMIERCONTACT_DELETE_REQUEST = 'PREMIERCONTACT_DELETE_REQUEST'
export const PREMIERCONTACT_DELETE_SUCCESS = 'PREMIERCONTACT_DELETE_SUCCESS'
export const PREMIERCONTACT_DELETE_FAIL = 'PREMIERCONTACT_DELETE_FAIL'



export const PREMIERCONTACT_LIST_REQUEST = 'PREMIERCONTACT_LIST_REQUEST'
export const PREMIERCONTACT_LIST_SUCCESS = 'PREMIERCONTACT_LIST_SUCCESS'
export const PREMIERCONTACT_LIST_FAIL = 'PREMIERCONTACT_LIST_FAIL'



export const PREMIERCONTACT_DETAILS_REQUEST = 'PREMIERCONTACT_DETAILS_REQUEST'
export const PREMIERCONTACT_DETAILS_SUCCESS = 'PREMIERCONTACT_DETAILS_SUCCESS'
export const PREMIERCONTACT_DETAILS_FAIL = 'PREMIERCONTACT_DETAILS_FAIL'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'


export const PREMIERCONTACT_UPDATE_REQUEST = 'PREMIERCONTACT_UPDATE_REQUEST'
export const PREMIERCONTACT_UPDATE_SUCCESS = 'PREMIERCONTACT_UPDATE_SUCCESS'
export const PREMIERCONTACT_UPDATE_FAIL = 'PREMIERCONTACT_UPDATE_FAIL'
export const PREMIERCONTACT_UPDATE_RESET = 'PREMIERCONTACT_UPDATE_RESET'